// Copyright (c) Choreo contributors

// Auto-generated by update_field_dimensions.py
package choreo.util;

class FieldDimensions {
  static final double FIELD_LENGTH = 3.6576;
  static final double FIELD_WIDTH = 3.6576;
}
